# Generated by Django 5.2.3 on 2025-06-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("second_name", models.CharField(max_length=100)),
                ("patronymic", models.CharField(blank=True, max_length=100, null=True)),
                ("class_number", models.IntegerField()),
                ("letter", models.CharField(max_length=2)),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
