# Generated by Django 5.2.3 on 2025-06-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("title", models.CharField(max_length=100)),
                ("body", models.CharField(blank=True)),
                ("creation_date", models.DateField(auto_now_add=True)),
                ("author_id", models.IntegerField(editable=False)),
                ("images", models.JSONField()),
                ("is_published", models.BooleanField()),
            ],
        ),
    ]
