# Generated by Django 5.2.3 on 2025-06-24 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegularUser",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("registration_date", models.DateField(auto_now_add=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="author_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="api.regularuser",
            ),
        ),
    ]
