# Generated by Django 5.2.3 on 2025-06-24 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_regularuser_alter_post_body_alter_post_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="author_id",
            new_name="author",
        ),
    ]
