# Generated by Django 5.2.3 on 2025-06-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_author_id_post_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
