# Generated by Django 5.2.3 on 2025-06-25 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_post_is_published"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.DeleteModel(
            name="RegularUser",
        ),
    ]
